title: "Hall-of-Apps"
description: "The Top Android Apps Metadata Archive"
table_contents:
  - Publications
  - Technologies
  - Dataset
  - Metrics and Statistics

show_downloads: true

tools_repo: https://github.com/TheSoftwareDesignLab/hall-of-apps-tools
dataset_doi: https://doi.org/10.5281/zenodo.3653367

logo1: /assets/imgs/structural/andes.png
tsdllogo: /assets/imgs/structural/tsdl.png

theme: jekyll-theme-minimal
