title: "Hall-of-Apps: The Top Android Apps Metadata Archive"
table_contents:
  - Publications
  - Technologies
  - Parser
  - Database
  - Metrics

logo1: /assets/imgs/structural/andes.png
tsdllogo: /assets/imgs/structural/tsdl.png

theme: jekyll-theme-minimal